Added announcement details component
CertainlyAUser/Practica_Echipa3_Frontend pull request #12
Opened 2020-12-09 21:13 UTC by Razulea

Adaugat doar componenta de announcement details

2020-12-10 14:11 UTC, sekilm requested changes
Schimba te rog linia aia si dam PR dupa, ca altfel vad ca nu-mi mai merge pagina mea =))

2020-12-10 14:11 UTC, sekilm commented on src/app/components/announcement-details/announcement-details.component.html
> +<link rel="stylesheet" href="announcement-details.component.css">
Nu-i nevoie sa adaugi link rel, stie componenta singura de unde sa isi ia styling-u. Se vede in fisieru .ts la styleUrls de mai jos
```suggestion
<link rel="stylesheet" href="announcement-details.component.css">

@Component({
    selector: 'app-announcement-details',
    templateUrl: './announcement-details.component.html',
    styleUrls: ['./announcement-details.component.css']
})
```

2020-12-10 14:58 UTC, sekilm approved these changes

2020-12-11 22:34 UTC, CertainlyAUser requested changes
Announcement details nu este o component ci o pagina asa ca nu va avea input ci un service care face un GET request catre back. Service-ul va lua id-ul anuntului din ActivatedRoute folosind ceva de genul "this.route.snapshot.paramMap.get('id');"

2020-12-17 14:34 UTC, CertainlyAUser approved these changes

2020-12-17 14:34 UTC, merged